use crate::types::errors::AstraError;

pub struct PlanningService;

impl PlanningService {
    pub fn new() -> Self {
        Self
    }

    pub async fn generate_daily_plan(&self) -> Result<String, AstraError> {
        Ok("Mock study plan generated by PlanningService.".to_string())
    }
}
